name: Test
permisssions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        id: test
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.jks
